/-
  PlufWO5/PartB.lean — Work Order 5, Part B: the block filter at ω and the
  membership / addability criteria (Paper II, Definition 3.1, Lemma 3.2).
-/
import RequestProject.PlufWO5.Basic

open Set

set_option synthInstance.maxHeartbeats 1000000

namespace PlufWO5

open PlufWO1

noncomputable section

/-- The block filter of `U` at ω: generated by the blocks of `U`-sets
    together with the closed subspaces of finite codimension. Membership
    unfolds to: some generating intersection `block S ⊓ V` sits inside. -/
def PhiOmega (U : Ultrafilter ℕ) (M : Submodule ℝ H) : Prop :=
  ∃ S ∈ U, ∃ V : Submodule ℝ H,
    IsClosed (V : Set H) ∧ Module.Finite ℝ ↥Vᗮ ∧ block S ⊓ V ≤ M

/-- B1 (Lemma 3.2(a)). Membership criterion:
    `M ∈ Φ(U)` iff `M` has finite relative codimension in some
    `U`-block. (⇐ is the paper's `V = (M ⊓ block S) ⊕ block Sᶜ`
    construction, rendered as `V = ((M ⊓ block S)ᗮ ⊓ block S)ᗮ`, which is
    manifestly closed; ⇒ is monotonicity of relative codimension.) -/
theorem phiOmega_iff_finCodim (U : Ultrafilter ℕ) (M : Submodule ℝ H)
    (hM : IsClosed (M : Set H)) :
    PhiOmega U M ↔ ∃ S ∈ U, FinCodimIn M (block S) := by
  constructor
  · rintro ⟨S, hSU, V, hVclosed, hVfin, hle⟩
    refine ⟨S, hSU, ?_⟩
    have hKclosed : IsClosed ((M ⊓ block S : Submodule ℝ H) : Set H) :=
      isClosed_inf hM (isClosed_block S)
    rw [finCodimIn_iff_finite_orthocomplement M (block S) hKclosed]
    refine finite_of_trivial_on_finite_codim _ V hVclosed hVfin (fun r hr hrV => ?_)
    have hrK : r ∈ M ⊓ block S := ⟨hle ⟨hr.2, hrV⟩, hr.2⟩
    have : r ∈ (M ⊓ block S) ⊓ (M ⊓ block S)ᗮ := ⟨hrK, hr.1⟩
    rw [Submodule.inf_orthogonal_eq_bot] at this
    simpa using this
  · rintro ⟨S, hSU, hcodim⟩
    have hKclosed : IsClosed ((M ⊓ block S : Submodule ℝ H) : Set H) :=
      isClosed_inf hM (isClosed_block S)
    haveI : CompleteSpace ↥(M ⊓ block S) := hKclosed.completeSpace_coe
    rw [finCodimIn_iff_finite_orthocomplement M (block S) hKclosed] at hcodim
    haveI : Module.Finite ℝ ↥((M ⊓ block S)ᗮ ⊓ block S) := hcodim
    haveI : FiniteDimensional ℝ ↥((M ⊓ block S)ᗮ ⊓ block S) := hcodim
    refine ⟨S, hSU, ((M ⊓ block S)ᗮ ⊓ block S)ᗮ, Submodule.isClosed_orthogonal _, ?_, ?_⟩
    · rw [Submodule.orthogonal_orthogonal]
      exact hcodim
    · rintro x ⟨hxS, hxV⟩
      set K : Submodule ℝ H := M ⊓ block S with hK
      set p : H := K.starProjection x with hp
      have hpK : p ∈ K := Submodule.starProjection_apply_mem K x
      have hrK : x - p ∈ Kᗮ := Submodule.sub_starProjection_mem_orthogonal x
      have hrS : x - p ∈ block S := Submodule.sub_mem _ hxS hpK.2
      have hrR : x - p ∈ Kᗮ ⊓ block S := ⟨hrK, hrS⟩
      have h1 : inner (𝕜 := ℝ) x (x - p) = 0 := by
        have := hxV (x - p) hrR
        rw [real_inner_comm] at this
        exact this
      have h2 : inner (𝕜 := ℝ) p (x - p) = 0 := by
        have := hrK p hpK
        exact this
      have h3 : inner (𝕜 := ℝ) (x - p) (x - p) = 0 := by
        rw [inner_sub_left, h1, h2, sub_zero]
      have : x - p = 0 := inner_self_eq_zero.mp h3
      have hxp : x = p := by linear_combination (norm := module) this
      rw [hxp]
      exact hpK.1

/-- B2 (Lemma 3.2(b)). Addability criterion: `M` meets every member of
    `Φ(U)` nontrivially iff `M ⊓ block S` is infinite-dimensional for
    every `S ∈ U`.

    Note: the contract hypotheses `hcof` and `hM` are retained as stated,
    but neither is consumed: an infinite-dimensional subspace meets every
    finite-codimension member of a generating intersection, and in the
    other direction a finite-dimensional `M ⊓ block S` is itself closed,
    so `block S ⊓ (M ⊓ block S)ᗮ` is the required member. -/
theorem addable_iff_infDim (U : Ultrafilter ℕ)
    (hcof : ∀ n : ℕ, ({n}ᶜ : Set ℕ) ∈ U) (M : Submodule ℝ H)
    (hM : IsClosed (M : Set H)) :
    (∀ N : Submodule ℝ H, PhiOmega U N → M ⊓ N ≠ ⊥) ↔
      (∀ S ∈ U, ¬ Module.Finite ℝ ↥(M ⊓ block S)) := by
  constructor
  · intro h S hSU hfin
    haveI : Module.Finite ℝ ↥(M ⊓ block S) := hfin
    haveI : FiniteDimensional ℝ ↥(M ⊓ block S) := hfin
    set K : Submodule ℝ H := M ⊓ block S with hK
    refine h (block S ⊓ Kᗮ) ⟨S, hSU, Kᗮ, Submodule.isClosed_orthogonal _, ?_, le_rfl⟩ ?_
    · rw [Submodule.orthogonal_orthogonal]
      exact hfin
    · rw [Submodule.eq_bot_iff]
      rintro x ⟨hxM, hxS, hxK⟩
      have : x ∈ K ⊓ Kᗮ := ⟨⟨hxM, hxS⟩, hxK⟩
      rw [Submodule.inf_orthogonal_eq_bot] at this
      simpa using this
  · rintro h N ⟨S, hSU, V, hVclosed, hVfin, hle⟩ hbot
    have hne := inf_ne_bot_of_not_finite (M ⊓ block S) V hVclosed hVfin (h S hSU)
    obtain ⟨x, hx, hx0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hne
    refine hx0 ?_
    have hxN : x ∈ N := hle ⟨hx.1.2, hx.2⟩
    have : x ∈ M ⊓ N := ⟨hx.1.1, hxN⟩
    rw [hbot] at this
    simpa using this

/-- B3 (properness). `⊥ ∉ Φ(U)`, given `hcof`. -/
theorem bot_not_phiOmega (U : Ultrafilter ℕ)
    (hcof : ∀ n : ℕ, ({n}ᶜ : Set ℕ) ∈ U) :
    ¬ PhiOmega U (⊥ : Submodule ℝ H) := by
  rintro ⟨S, hSU, V, hVclosed, hVfin, hle⟩
  have hSinf : S.Infinite := infinite_of_mem U hcof hSU
  have hne := inf_ne_bot_of_not_finite (block S) V hVclosed hVfin (not_finite_block hSinf)
  exact hne (le_bot_iff.mp hle)

end

end PlufWO5
