/-
  PlufWO6/PartA.lean — Work Order 6, Part A: the structure lemmas
  (Paper I, Lemmas 2.1 and 2.2).

  A1 and A5 are returned under the codified counterexample licence: over
  the zero space the empty family satisfies `IsPluf`, and both contracted
  statements fail for it. The marked minimal repair adds `[Nontrivial E]`
  (i.e. `H ≠ 0`, which the paper assumes throughout: `H` is separable and
  infinite-dimensional). Everything else is proved as contracted.
-/
import RequestProject.PlufWO6.Basic

open Set
open scoped Classical

set_option synthInstance.maxHeartbeats 1000000

namespace PlufWO6

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-! ### Part A: the structure lemmas -/

/-  A1, contract statement, preserved verbatim:

theorem maximality_criterion (π : Set (Submodule ℝ E)) (hπ : IsPluf π) :
    ∀ M : Submodule ℝ E, IsClosed (M : Set E) →
      M ∈ π ∨ ∃ N ∈ π, M ⊓ N = ⊥

    This form is not provable over the zero space: there every submodule
    is `⊥`, so the empty family `π = ∅` satisfies all five clauses of
    `IsPluf` (the maximality clause because a proper family of subspaces
    of the zero space is empty), while for `M = ⊥` neither disjunct
    holds — see `isPluf_empty_zero_space` below. The marked minimal
    repair assumes `E ≠ 0`, which is the paper's standing hypothesis on
    `H`; the argument then produces the missing member of `π`, namely
    `⊤` (`IsPluf.top_mem`). -/

/-- The obstruction to the contract form of A1 (and of A5, C2, D2): over
    the zero space the empty family is a pluf, and the maximality
    criterion fails for it at `M = ⊥`. -/
theorem isPluf_empty_zero_space :
    IsPluf (E := EuclideanSpace ℝ (Fin 0)) ∅ ∧
      ¬ (∀ M : Submodule ℝ (EuclideanSpace ℝ (Fin 0)),
          IsClosed (M : Set (EuclideanSpace ℝ (Fin 0))) →
            M ∈ (∅ : Set (Submodule ℝ (EuclideanSpace ℝ (Fin 0)))) ∨
              ∃ N ∈ (∅ : Set (Submodule ℝ (EuclideanSpace ℝ (Fin 0)))), M ⊓ N = ⊥) := by
  constructor
  · refine ⟨by simp, by simp, by simp, by simp, ?_⟩
    intro σ _ _ _ hbot M hM
    exact absurd (by simpa [Subsingleton.elim M (⊥ : Submodule ℝ (EuclideanSpace ℝ (Fin 0)))]
      using hM) hbot
  · intro h
    rcases h ⊥ (by simp) with h | ⟨N, hN, -⟩
    · exact h
    · exact hN

/-- A1 (Lemma 2.1; the maximality criterion), minimal repair: `E ≠ 0`.
    A filter of closed subspaces is maximal iff every closed subspace
    either belongs to it or meets some member trivially. This is the
    criterion every later paper cites; it is the single most-used fact of
    the series.

    Proof (paper): the filter generated by `π ∪ {M}` consists of the closed
    subspaces containing some `M ⊓ N`, `N ∈ π`, and is proper exactly when
    no such meet is `⊥`. -/
theorem maximality_criterion [Nontrivial E] (π : Set (Submodule ℝ E)) (hπ : IsPluf π) :
    ∀ M : Submodule ℝ E, IsClosed (M : Set E) →
      M ∈ π ∨ ∃ N ∈ π, M ⊓ N = ⊥ := by
  intro M hM
  by_cases hex : ∃ N ∈ π, M ⊓ N = ⊥
  · exact Or.inr hex
  push_neg at hex
  refine Or.inl ?_
  -- the family generated by `π ∪ {M}`
  set σ : Set (Submodule ℝ E) := π ∪ (fun N => M ⊓ N) '' π with hσ
  have hmem : ∀ K ∈ σ, K ∈ π := by
    refine hπ.maximal σ ?_ (fun K hK => Or.inl hK) ?_ ?_
    · rintro K (hK | ⟨N, hN, rfl⟩)
      · exact hπ.mem_closed K hK
      · exact isClosed_inf hM (hπ.mem_closed N hN)
    · rintro K (hK | ⟨N, hN, rfl⟩) K' (hK' | ⟨N', hN', rfl⟩)
      · exact Or.inl (hπ.inf_mem K hK K' hK')
      · refine Or.inr ⟨K ⊓ N', hπ.inf_mem K hK N' hN', ?_⟩
        rw [inf_comm K (M ⊓ N'), inf_assoc, inf_comm N' K]
      · exact Or.inr ⟨N ⊓ K', hπ.inf_mem N hN K' hK', by rw [inf_assoc]⟩
      · refine Or.inr ⟨N ⊓ N', hπ.inf_mem N hN N' hN', ?_⟩
        exact inf_inf_distrib_left M N N'
    · rintro (hbot | ⟨N, hN, hbot⟩)
      · exact hπ.proper hbot
      · exact hex N hN hbot
  have : M ⊓ ⊤ ∈ σ := Or.inr ⟨⊤, hπ.top_mem, rfl⟩
  simpa using hmem _ this

/-- A2 (converse half, for building plufs). A proper, upward closed,
    meet-closed family of closed subspaces satisfying the criterion is a
    pluf. (Together A1/A2 are the working form of Lemma 2.1; WO-5's
    `PlufPackage` is exactly the conjunction, which is why Part G is a
    corollary of this pair.) -/
theorem isPluf_of_criterion (π : Set (Submodule ℝ E))
    (hcl : ∀ M ∈ π, IsClosed (M : Set E))
    (hup : ∀ M ∈ π, ∀ N : Submodule ℝ E, IsClosed (N : Set E) → M ≤ N → N ∈ π)
    (hinf : ∀ M ∈ π, ∀ N ∈ π, M ⊓ N ∈ π)
    (hbot : (⊥ : Submodule ℝ E) ∉ π)
    (hdec : ∀ M : Submodule ℝ E, IsClosed (M : Set E) →
      M ∈ π ∨ ∃ N ∈ π, M ⊓ N = ⊥) :
    IsPluf π := by
  refine ⟨hcl, hup, hinf, hbot, ?_⟩
  intro σ hσcl hσsup hσinf hσbot M hM
  rcases hdec M (hσcl M hM) with h | ⟨N, hN, hNbot⟩
  · exact h
  · exact absurd (hNbot ▸ hσinf M hM N (hσsup N hN)) hσbot

/-- A3 (Lemma 2.2, first half). A pluf containing a finite-dimensional
    subspace is the principal pluf of a line: a member of least finite
    dimension `d` is contained in every member; `d ≥ 2` would let a proper
    line inside it meet every member, contradicting maximality. -/
theorem principal_of_finiteDimensional (π : Set (Submodule ℝ E)) (hπ : IsPluf π)
    (M : Submodule ℝ E) (hM : M ∈ π) (hfin : Module.Finite ℝ ↥M) :
    ∃ L : Submodule ℝ E, Module.finrank ℝ ↥L = 1 ∧
      ∀ N : Submodule ℝ E, IsClosed (N : Set E) → (N ∈ π ↔ L ≤ N) := by
  classical
  -- the set of finite dimensions of members of `π`
  set D : Set ℕ := {n | ∃ K ∈ π, ∃ _ : Module.Finite ℝ ↥K, Module.finrank ℝ ↥K = n} with hD
  have hDne : D.Nonempty := ⟨Module.finrank ℝ ↥M, M, hM, hfin, rfl⟩
  obtain ⟨K, hK, hKfin, hKrank⟩ : sInf D ∈ D := Nat.sInf_mem hDne
  have hKle : ∀ N ∈ π, K ≤ N := by
    intro N hN
    have hinf : K ⊓ N ∈ π := hπ.inf_mem K hK N hN
    haveI : FiniteDimensional ℝ ↥K := hKfin
    haveI : FiniteDimensional ℝ ↥(K ⊓ N) := Submodule.finiteDimensional_of_le inf_le_left
    have h1 : Module.finrank ℝ ↥(K ⊓ N) ≤ Module.finrank ℝ ↥K :=
      Submodule.finrank_mono inf_le_left
    have h2 : sInf D ≤ Module.finrank ℝ ↥(K ⊓ N) :=
      Nat.sInf_le ⟨K ⊓ N, hinf, inferInstance, rfl⟩
    have h3 : Module.finrank ℝ ↥(K ⊓ N) = Module.finrank ℝ ↥K := le_antisymm h1 (hKrank ▸ h2)
    have : K ⊓ N = K := Submodule.eq_of_le_of_finrank_eq inf_le_left h3
    exact this ▸ inf_le_right
  haveI : FiniteDimensional ℝ ↥K := hKfin
  have hKne : K ≠ ⊥ := hπ.ne_bot hK
  have hpos : 1 ≤ Module.finrank ℝ ↥K := by
    rcases Nat.eq_zero_or_pos (Module.finrank ℝ ↥K) with h | h
    · exact absurd (Submodule.finrank_eq_zero.mp h) hKne
    · exact h
  have hrank : Module.finrank ℝ ↥K = 1 := by
    by_contra hne
    have h2 : 2 ≤ Module.finrank ℝ ↥K := by omega
    -- a line inside `K` lies in every member of `π`, so maximality puts it into `π`
    obtain ⟨v, hvK, hv0⟩ : ∃ v ∈ K, v ≠ 0 := by
      obtain ⟨v, hv⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hKne
      exact ⟨v, hv.1, hv.2⟩
    set L : Submodule ℝ E := Submodule.span ℝ {v} with hL
    have hLrank : Module.finrank ℝ ↥L = 1 := finrank_span_singleton hv0
    haveI : FiniteDimensional ℝ ↥L := by
      apply FiniteDimensional.span_singleton
    have hLK : L ≤ K := by
      rw [hL, Submodule.span_le, Set.singleton_subset_iff]; exact hvK
    have hLcl : IsClosed (L : Set E) := Submodule.closed_of_finiteDimensional L
    have hLbot : L ≠ ⊥ := by
      intro h
      rw [h] at hLrank
      simp at hLrank
    have hLmem : L ∈ π := by
      refine hπ.maximal (π ∪ {L}) ?_ (fun N hN => Or.inl hN) ?_ ?_ L (Or.inr rfl)
      · rintro N (hN | rfl)
        · exact hπ.mem_closed N hN
        · exact hLcl
      · rintro N (hN | rfl) N' (hN' | rfl)
        · exact Or.inl (hπ.inf_mem N hN N' hN')
        · rw [inf_comm]
          exact Or.inr (by
            simp only [Set.mem_singleton_iff]
            exact inf_eq_left.mpr (hLK.trans (hKle N hN)))
        · exact Or.inr (by
            simp only [Set.mem_singleton_iff]
            exact inf_eq_left.mpr (hLK.trans (hKle N' hN')))
        · exact Or.inr (by simp)
      · rintro (hbot | hbot)
        · exact hπ.proper hbot
        · exact hLbot (by simpa using hbot.symm)
    have : sInf D ≤ 1 := Nat.sInf_le ⟨L, hLmem, inferInstance, hLrank⟩
    omega
  refine ⟨K, hrank, fun N hNcl => ⟨fun hN => hKle N hN, fun hle => hπ.upward K hK N hNcl hle⟩⟩

/-- A4 (Lemma 2.2, second half). A pluf is principal iff its intersection
    is nonzero. -/
theorem principal_iff_sInf_ne_bot (π : Set (Submodule ℝ E)) (hπ : IsPluf π) :
    (∃ L : Submodule ℝ E, Module.finrank ℝ ↥L = 1 ∧
      ∀ N : Submodule ℝ E, IsClosed (N : Set E) → (N ∈ π ↔ L ≤ N)) ↔
    ∃ v : E, v ≠ 0 ∧ ∀ M ∈ π, v ∈ M := by
  constructor
  · rintro ⟨L, hL1, hL⟩
    have hLbot : L ≠ ⊥ := by
      intro h
      rw [h] at hL1
      simp at hL1
    obtain ⟨v, hvL, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hLbot
    refine ⟨v, hv0, fun M hM => ?_⟩
    exact (hL M (hπ.mem_closed M hM)).mp hM hvL
  · rintro ⟨v, hv0, hv⟩
    classical
    set L : Submodule ℝ E := Submodule.span ℝ {v} with hLdef
    have hLrank : Module.finrank ℝ ↥L = 1 := finrank_span_singleton hv0
    haveI : FiniteDimensional ℝ ↥L := FiniteDimensional.span_singleton ℝ v
    have hLcl : IsClosed (L : Set E) := Submodule.closed_of_finiteDimensional L
    have hLbot : L ≠ ⊥ := by
      intro h
      rw [h] at hLrank
      simp at hLrank
    have hLle : ∀ M ∈ π, L ≤ M := by
      intro M hM
      rw [hLdef, Submodule.span_le, Set.singleton_subset_iff]
      exact hv M hM
    have hLmem : L ∈ π := by
      refine hπ.maximal (π ∪ {L}) ?_ (fun N hN => Or.inl hN) ?_ ?_ L (Or.inr rfl)
      · rintro N (hN | rfl)
        · exact hπ.mem_closed N hN
        · exact hLcl
      · rintro N (hN | rfl) N' (hN' | rfl)
        · exact Or.inl (hπ.inf_mem N hN N' hN')
        · rw [inf_comm]
          exact Or.inr (by
            simp only [Set.mem_singleton_iff]
            exact inf_eq_left.mpr (hLle N hN))
        · exact Or.inr (by
            simp only [Set.mem_singleton_iff]
            exact inf_eq_left.mpr (hLle N' hN'))
        · exact Or.inr (by simp)
      · rintro (hbot | hbot)
        · exact hπ.proper hbot
        · exact hLbot (by simpa using hbot.symm)
    refine ⟨L, hLrank, fun N hNcl => ⟨fun hN => hLle N hN, fun hle => hπ.upward L hLmem N hNcl hle⟩⟩

/-  A5, contract statement, preserved verbatim:

theorem finCodim_mem_of_nonprincipal (π : Set (Submodule ℝ E)) (hπ : IsPluf π)
    (hnp : ∀ v : E, v ≠ 0 → ∃ M ∈ π, v ∉ M)
    (V : Submodule ℝ E) (hV : IsClosed (V : Set E))
    (hfc : Module.Finite ℝ ↥Vᗮ) :
    V ∈ π

    As with A1, this fails over the zero space (`π = ∅`, `V = ⊥`, the
    nonprincipality hypothesis vacuous); the marked minimal repair adds
    `[Nontrivial E]`. -/

/-- A5 (Lemma 2.2, third half; the fact WO-5's package needs), minimal
    repair: `E ≠ 0`. A nonprincipal pluf contains every closed subspace of
    finite codimension: otherwise some member meets it trivially and is
    therefore finite-dimensional, forcing principality by A3. -/
theorem finCodim_mem_of_nonprincipal [Nontrivial E] (π : Set (Submodule ℝ E)) (hπ : IsPluf π)
    (hnp : ∀ v : E, v ≠ 0 → ∃ M ∈ π, v ∉ M)
    (V : Submodule ℝ E) (hV : IsClosed (V : Set E))
    (hfc : Module.Finite ℝ ↥Vᗮ) :
    V ∈ π := by
  rcases maximality_criterion π hπ V hV with h | ⟨N, hN, hNbot⟩
  · exact h
  -- `N` injects into `Vᗮ` under the orthogonal projection, hence is finite-dimensional
  haveI : CompleteSpace ↥V := hV.completeSpace_coe
  haveI : FiniteDimensional ℝ ↥Vᗮ := hfc
  have hinj : Function.Injective
      (((Vᗮ).orthogonalProjection : E →L[ℝ] ↥Vᗮ).toLinearMap.comp N.subtype) := by
    rw [← LinearMap.ker_eq_bot]
    rw [Submodule.eq_bot_iff]
    rintro ⟨x, hx⟩ hker
    have hx0 : (Vᗮ).orthogonalProjection x = 0 := by
      simpa using hker
    have hxV : x ∈ V := by
      have hmem := Submodule.orthogonalProjection_eq_zero_iff.mp hx0
      rwa [Submodule.orthogonal_orthogonal V] at hmem
    have : x ∈ V ⊓ N := ⟨hxV, hx⟩
    rw [hNbot] at this
    simpa using this
  haveI : FiniteDimensional ℝ ↥N := FiniteDimensional.of_injective _ hinj
  obtain ⟨L, hL1, hL⟩ := principal_of_finiteDimensional π hπ N hN inferInstance
  have hLbot : L ≠ ⊥ := by
    intro h
    rw [h] at hL1
    simp at hL1
  obtain ⟨v, hvL, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hLbot
  obtain ⟨M, hM, hvM⟩ := hnp v hv0
  exact absurd ((hL M (hπ.mem_closed M hM)).mp hM hvL) hvM

end PlufWO6
