/-
  PlufWO16/PartB.lean — Work Order 16, Part B: the diagonal block
  (Paper V, Section 7).

  B1 the description of `cD` by supports and downward closure of `cI`;
  B2 the trace formula, both halves;
  B3 diagonal consistency as membership in a pluf with ultrafilter trace;
  B4 the covering criterion.
-/
import RequestProject.PlufWO16.Basic

open Set

namespace PlufWO16

/-! ### B1: `cD` from the support family -/

/-- B1 (Paper V, Lemma 7.2). `S ∈ cD M` exactly when `S` contains the support
    of a nonzero vector of `M`. -/
theorem mem_cD_iff (M : Submodule ℝ H) (S : Set ℕ) :
    S ∈ cD M ↔ ∃ x ∈ M, x ≠ 0 ∧ supp x ⊆ S := by
  constructor
  · intro hS
    obtain ⟨x, hx, hx0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot (show M ⊓ PlufWO1.block S ≠ ⊥ from hS)
    exact ⟨x, hx.1, hx0, (mem_block_iff_supp_subset S x).1 hx.2⟩
  · rintro ⟨x, hxM, hx0, hxS⟩
    intro hbot
    apply hx0
    have hmem : x ∈ M ⊓ PlufWO1.block S :=
      ⟨hxM, (mem_block_iff_supp_subset S x).2 hxS⟩
    rw [hbot] at hmem
    simpa using hmem

/-- B1 (Paper V, Lemma 7.2, second clause). `cI M` is downward closed. -/
theorem cI_downward (M : Submodule ℝ H) {S T : Set ℕ} (hS : S ∈ cI M) (hTS : T ⊆ S) :
    T ∈ cI M := by
  have hle : M ⊓ PlufWO1.block T ≤ M ⊓ PlufWO1.block S :=
    inf_le_inf_left _ (PlufWO5.block_mono hTS)
  have : M ⊓ PlufWO1.block T ≤ ⊥ := by
    rw [← show M ⊓ PlufWO1.block S = ⊥ from hS]; exact hle
  exact le_bot_iff.mp this

/-- The empty set is independent for every `M`. -/
theorem empty_mem_cI (M : Submodule ℝ H) : (∅ : Set ℕ) ∈ cI M := by
  show M ⊓ PlufWO1.block (∅ : Set ℕ) = ⊥
  rw [PlufWO5.block_empty, inf_bot_eq]

/-! ### B2: the trace formula -/

/-- B2 (Paper V, Proposition 7.3, the inclusion `⊆`). -/
theorem trace_subset (π : Set (Submodule ℝ H)) (hπ : PlufWO6.IsPluf π)
    {S : Set ℕ} (hS : PlufWO1.block S ∈ π) (M : Submodule ℝ H) (hM : M ∈ π) :
    S ∈ cD M :=
  hπ.inf_ne_bot hM hS

/-- B2 (Paper V, Proposition 7.3, equality under maximality). -/
theorem mem_trace_of_forall_cD (π : Set (Submodule ℝ H)) (hπ : PlufWO6.IsPluf π)
    {S : Set ℕ} (hS : ∀ M ∈ π, S ∈ cD M) :
    PlufWO1.block S ∈ π := by
  haveI := PlufWO6.nontrivial_H
  rcases PlufWO6.maximality_criterion π hπ (PlufWO1.block S) (PlufWO1.isClosed_block S) with
    h | ⟨N, hN, hbot⟩
  · exact h
  · exact absurd (by rw [inf_comm]; exact hbot) (hS N hN)

/-! ### B3: diagonal consistency and plufs with ultrafilter trace -/

/-- The proper filter generated by `M` and the blocks of an ultrafilter
    contained in `cD M`: the closed subspaces above some `M ⊓ block S`,
    `S ∈ U`. -/
def genFilter (M : Submodule ℝ H) (U : Ultrafilter ℕ) : Set (Submodule ℝ H) :=
  {K : Submodule ℝ H | IsClosed (K : Set H) ∧ ∃ S ∈ U, M ⊓ PlufWO1.block S ≤ K}

theorem isProperFilter_genFilter (M : Submodule ℝ H)
    (U : Ultrafilter ℕ) (hU : ∀ S ∈ U, S ∈ cD M) :
    PlufWO10.IsProperFilter (genFilter M U) := by
  refine ⟨fun K hK => hK.1, ⟨⊤, ?_⟩, ?_, ?_, ?_⟩
  · exact ⟨by simp, univ, Filter.univ_mem, le_top⟩
  · rintro K ⟨-, S, hS, hle⟩ K' hK' hKK'
    exact ⟨hK', S, hS, hle.trans hKK'⟩
  · rintro K ⟨hKc, S, hS, hleS⟩ K' ⟨hK'c, T, hT, hleT⟩
    refine ⟨PlufWO6.isClosed_inf hKc hK'c, S ∩ T, Filter.inter_mem hS hT, ?_⟩
    rw [PlufWO5.block_inter]
    exact le_inf ((inf_le_inf_left M inf_le_left).trans hleS)
      ((inf_le_inf_left M inf_le_right).trans hleT)
  · rintro ⟨-, S, hS, hle⟩
    exact hU S hS (le_bot_iff.mp hle)

/-- B3 (Paper V, Proposition 7.5). -/
theorem diagonallyConsistent_iff (M : Submodule ℝ H) (hM : IsClosed (M : Set H)) :
    DiagonallyConsistent M ↔
      ∃ π, PlufWO6.IsPluf π ∧ M ∈ π ∧
        ∃ U : Ultrafilter ℕ, ∀ S : Set ℕ, S ∈ U ↔ PlufWO1.block S ∈ π := by
  constructor
  · rintro ⟨U, hU⟩
    obtain ⟨π, hπ, hsub⟩ :=
      PlufWO10.exists_pluf_extension (genFilter M U) (isProperFilter_genFilter M U hU)
    have hMπ : M ∈ π := hsub ⟨hM, univ, Filter.univ_mem, inf_le_left⟩
    refine ⟨π, hπ, hMπ, U, fun S => ⟨fun hS => ?_, fun hS => ?_⟩⟩
    · exact hsub ⟨PlufWO1.isClosed_block S, S, hS, inf_le_right⟩
    · by_contra hSU
      have hcompl : Sᶜ ∈ U := Ultrafilter.compl_mem_iff_notMem.mpr hSU
      have hblock : PlufWO1.block Sᶜ ∈ π :=
        hsub ⟨PlufWO1.isClosed_block Sᶜ, Sᶜ, hcompl, inf_le_right⟩
      have hbot : (⊥ : Submodule ℝ H) ∈ π := by
        have := hπ.inf_mem _ hS _ hblock
        rwa [← PlufWO5.block_inter, inter_compl_self, PlufWO5.block_empty] at this
      exact hπ.proper hbot
  · rintro ⟨π, hπ, hMπ, U, hU⟩
    exact ⟨U, fun S hS => trace_subset π hπ ((hU S).1 hS) M hMπ⟩

/-! ### B4: the covering criterion -/

/-- The filter of complements of finite unions of members of `cI M`. -/
def coverFilter (M : Submodule ℝ H) : Filter ℕ where
  sets := {T : Set ℕ | ∃ F : Finset (Set ℕ), (∀ S ∈ F, S ∈ cI M) ∧ (⋃ S ∈ F, S)ᶜ ⊆ T}
  univ_sets := ⟨∅, by simp, by simp⟩
  sets_of_superset := by
    rintro T T' ⟨F, hF, hsub⟩ hTT'
    exact ⟨F, hF, hsub.trans hTT'⟩
  inter_sets := by
    classical
    rintro T T' ⟨F, hF, hsub⟩ ⟨F', hF', hsub'⟩
    have hmono : ∀ G G' : Finset (Set ℕ), G ⊆ G' → (⋃ S ∈ G', S)ᶜ ⊆ (⋃ S ∈ G, S)ᶜ := by
      intro G G' hGG'
      apply compl_subset_compl.mpr
      intro n hn
      simp only [mem_iUnion, exists_prop] at hn ⊢
      obtain ⟨S, hSG, hnS⟩ := hn
      exact ⟨S, hGG' hSG, hnS⟩
    refine ⟨F ∪ F', ?_, subset_inter ?_ ?_⟩
    · intro S hS
      rcases Finset.mem_union.mp hS with h | h
      · exact hF S h
      · exact hF' S h
    · exact (hmono F (F ∪ F') Finset.subset_union_left).trans hsub
    · exact (hmono F' (F ∪ F') Finset.subset_union_right).trans hsub'

theorem neBot_coverFilter (M : Submodule ℝ H) (h : ¬ HasFiniteCover M) :
    (coverFilter M).NeBot := by
  rw [Filter.neBot_iff]
  intro hbot
  have : (∅ : Set ℕ) ∈ coverFilter M := by rw [hbot]; trivial
  obtain ⟨F, hF, hsub⟩ := this
  exact h ⟨F, hF, compl_empty_iff.mp (subset_empty_iff.mp hsub)⟩

/-- B4 (Paper V, Theorem 7.6). -/
theorem diagonallyConsistent_iff_not_finiteCover (M : Submodule ℝ H) :
    DiagonallyConsistent M ↔ ¬ HasFiniteCover M := by
  constructor
  · rintro ⟨U, hU⟩ ⟨F, hF, hcov⟩
    have hmem : (⋃ S ∈ F, S) ∈ U := by rw [hcov]; exact Filter.univ_mem
    obtain ⟨S, hSF, hSU⟩ := (Ultrafilter.finite_biUnion_mem_iff F.finite_toSet).1 hmem
    exact (mem_cD_iff_notMem_cI M S).1 (hU S hSU) (hF S hSF)
  · intro hcov
    haveI := neBot_coverFilter M hcov
    refine ⟨Ultrafilter.of (coverFilter M), fun T hT => ?_⟩
    rw [mem_cD_iff_notMem_cI]
    intro hTI
    have hcompl : Tᶜ ∈ coverFilter M := ⟨{T}, by simpa using hTI, by simp⟩
    have : Tᶜ ∈ Ultrafilter.of (coverFilter M) := Ultrafilter.of_le _ hcompl
    exact Ultrafilter.compl_mem_iff_notMem.mp this hT

end PlufWO16
