/-
  PlufWO10.lean — Work Order 10 for the pluf project (Feldman–Wilce).

  Scope: target (a) of the WO-7a census — Paper II's Section 5.5 and
  Section 6:
    (A) the Zorn extension theorem: every proper filter of closed
        subspaces extends to a pluf;
    (B) relative orthogonal complements of a countable nested chain, and
        the simultaneous coordinatization of such a chain;
    (C) intimacy of blocks for their own basis;
    (D) Proposition 6.1 ("Chains never suffice") as printed;
    (E) Proposition 5.5 (the one-witness reduction) as printed.

  This closes a whole target. The census estimates ~0.5 commission and
  reports that three of the four ingredients already exist:
  `PlufWO5.diagonalizable_iff_intimate` (repaired in WO-6, and available
  for genuine plufs as `PlufWO6.diagonalizable_iff_intimate_pluf`),
  `PlufWO6.principal_iff_sInf_ne_bot`, and `PlufWO5.Intimate`. New
  material: the Zorn extension (§A) and the chain complements (§B).

  Basis-relative work must use WO-9's `PlufWO9.blockB` and its API —
  including `PlufWO9`'s corrected countable-decomposition theorem (the
  arbitrary-index form is FALSE; see the WO-7a counterexample) and the
  definitional agreement of `blockB` at the standard basis with WO-1's
  `block`, which is what lets prior results transfer unchanged.

  Ground rules as in WO-1–WO-9, including the codified counterexample
  license. Base: the WO-9 artifact (168 theorems; CI runs #1–#9). All
  prior theorems must remain green.

  Toolchain: leanprover/lean4:v4.28.0, Mathlib pinned as in the repo.

  REPORT (summary; see REPORT-WO10.md):

  * Items B2 and D1 are contracted with conclusions asserting the
    existence of a `HilbertBasis ℕ ℝ E` over an arbitrary separable
    complete `E`. That is FALSE: `E = ℝ` is separable and complete and
    has no `ℕ`-indexed Hilbert basis, while the chain `M k = ⊤` satisfies
    every hypothesis. The counterexamples are formalized
    (`exists_basis_blocks_of_chain_false`, `chains_never_suffice_false`),
    the contracted statements are preserved verbatim in comments, and the
    marked minimal repair — the single extra hypothesis
    `hinf : ¬ FiniteDimensional ℝ E` — is proved under the contracted
    names.
  * WO-9's countable-decomposition theorem D4 asks for
    `⨆ n, M n = ⊤` (an *algebraic* join). No infinite orthogonal
    decomposition of a Hilbert space satisfies it, so B1/B2 are written
    against the density variant proved here as
    `PlufWO10.exists_hilbertBasis_of_orthogonal_family` (D4's proof, with
    the one use of the span hypothesis replaced by
    `(⨆ n, M n)ᗮ = ⊥`).
  * The E0 question is answered affirmatively: the basis-relative form of
    Theorem 5.2 is `diagonalizableB_iff_intimateB` below, proved from the
    basis-relative block lattice identities. E1 in fact needs only its
    easy direction (`intimateB_of_diagonalizableB`).
-/
import RequestProject.PlufWO9
import RequestProject.PlufWO10.Decomp

open Set

namespace PlufWO10

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-! ### Part A: the Zorn extension theorem -/

/-- A proper filter of closed subspaces: the hypotheses of a pluf minus
    maximality. (If WO-6 already provides this bundle under another name,
    reuse it and report; do not duplicate.) -/
structure IsProperFilter (π : Set (Submodule ℝ E)) : Prop where
  mem_closed : ∀ M ∈ π, IsClosed (M : Set E)
  nonempty : π.Nonempty
  upward : ∀ M ∈ π, ∀ N : Submodule ℝ E, IsClosed (N : Set E) → M ≤ N → N ∈ π
  inf_mem : ∀ M ∈ π, ∀ N ∈ π, M ⊓ N ∈ π
  bot_notMem : (⊥ : Submodule ℝ E) ∉ π

/-- A1 (Zorn extension). Every proper filter of closed subspaces is
    contained in a pluf.

    Route: Zorn on the proper filters containing `π`, ordered by
    inclusion. The union of a chain of proper filters is a proper filter
    — the only clause needing care is closure under meets, where two
    members of the union lie in a common element of the chain by
    directedness. Maximality of a Zorn-maximal element in the sense of
    `PlufWO6.IsPluf` then follows from `PlufWO6.isPluf_of_criterion`
    together with the observation that if some closed `M` neither belongs
    to `π` nor meets a member trivially, the filter generated by
    `π ∪ {M}` is a strictly larger proper filter.

    Note `PlufWO6.IsPluf`'s maximality clause is stated as "every
    intermediate proper family is contained in π"; deriving that from
    Zorn-maximality may be smoother via the criterion. Prover's choice,
    reported. -/
theorem exists_pluf_extension (π : Set (Submodule ℝ E)) (hπ : IsProperFilter π) :
    ∃ σ, PlufWO6.IsPluf σ ∧ π ⊆ σ := by
  classical
  set S : Set (Set (Submodule ℝ E)) := {τ | IsProperFilter τ ∧ π ⊆ τ} with hS
  have hchain : ∀ c ⊆ S, IsChain (· ⊆ ·) c → c.Nonempty → ∃ ub ∈ S, ∀ s ∈ c, s ⊆ ub := by
    intro c hcS hc hcne
    refine ⟨⋃₀ c, ⟨⟨?_, ?_, ?_, ?_, ?_⟩, ?_⟩, fun s hs => Set.subset_sUnion_of_mem hs⟩
    · rintro M ⟨τ, hτ, hM⟩
      exact (hcS hτ).1.mem_closed M hM
    · obtain ⟨τ, hτ⟩ := hcne
      obtain ⟨M, hM⟩ := (hcS hτ).1.nonempty
      exact ⟨M, τ, hτ, hM⟩
    · rintro M ⟨τ, hτ, hM⟩ N hN hMN
      exact ⟨τ, hτ, (hcS hτ).1.upward M hM N hN hMN⟩
    · rintro M ⟨τ, hτ, hM⟩ N ⟨τ', hτ', hN⟩
      rcases hc.total hτ hτ' with h | h
      · exact ⟨τ', hτ', (hcS hτ').1.inf_mem M (h hM) N hN⟩
      · exact ⟨τ, hτ, (hcS hτ).1.inf_mem M hM N (h hN)⟩
    · rintro ⟨τ, hτ, hbot⟩
      exact (hcS hτ).1.bot_notMem hbot
    · obtain ⟨τ, hτ⟩ := hcne
      exact fun M hM => ⟨τ, hτ, (hcS hτ).2 hM⟩
  obtain ⟨σ, hπσ, hmax⟩ := zorn_subset_nonempty S hchain π ⟨hπ, subset_rfl⟩
  obtain ⟨hσ, -⟩ := hmax.prop
  refine ⟨σ, ?_, hπσ⟩
  refine PlufWO6.isPluf_of_criterion σ hσ.mem_closed hσ.upward hσ.inf_mem hσ.bot_notMem ?_
  intro M hMcl
  by_contra hcon
  push_neg at hcon
  obtain ⟨hMσ, hmeet⟩ := hcon
  -- the filter generated by `σ ∪ {M}`
  set τ : Set (Submodule ℝ E) := {K | IsClosed (K : Set E) ∧ ∃ N ∈ σ, M ⊓ N ≤ K} with hτ
  have hτprop : IsProperFilter τ := by
    obtain ⟨N₀, hN₀⟩ := hσ.nonempty
    refine ⟨fun K hK => hK.1, ⟨M, hMcl, N₀, hN₀, inf_le_left⟩, ?_, ?_, ?_⟩
    · rintro K ⟨-, N, hN, hle⟩ K' hK' hKK'
      exact ⟨hK', N, hN, hle.trans hKK'⟩
    · rintro K ⟨hKcl, N, hN, hle⟩ K' ⟨hK'cl, N', hN', hle'⟩
      refine ⟨PlufWO6.isClosed_inf hKcl hK'cl, N ⊓ N', hσ.inf_mem N hN N' hN', ?_⟩
      refine le_inf ?_ ?_
      · exact le_trans (inf_le_inf_left M inf_le_left) hle
      · exact le_trans (inf_le_inf_left M inf_le_right) hle'
    · rintro ⟨-, N, hN, hle⟩
      exact hmeet N hN (le_bot_iff.mp hle)
  have hστ : σ ⊆ τ := fun K hK => ⟨hσ.mem_closed K hK, K, hK, inf_le_right⟩
  have hτS : τ ∈ S := ⟨hτprop, hπσ.trans hστ⟩
  have : τ ⊆ σ := hmax.le_of_ge hτS hστ
  obtain ⟨N₀, hN₀⟩ := hσ.nonempty
  exact hMσ (this ⟨hMcl, N₀, hN₀, inf_le_left⟩)

/-- A2 (the family form, which is what Proposition 5.5 consumes). A
    downward directed family of closed subspaces, all of whose finite
    intersections are infinite-dimensional, generates a proper filter and
    hence extends to a pluf. (Infinite-dimensionality of the finite
    intersections is what gives properness; directedness makes the
    generated family closed under meets.) -/
theorem exists_pluf_of_directed (R : Set (Submodule ℝ E))
    (hne : R.Nonempty)
    (hcl : ∀ M ∈ R, IsClosed (M : Set E))
    (hdir : ∀ M ∈ R, ∀ N ∈ R, ∃ P ∈ R, P ≤ M ⊓ N)
    (hinf : ∀ F : Finset (Submodule ℝ E), ↑F ⊆ R →
      ¬ Module.Finite ℝ ↥(F.inf id)) :
    ∃ σ, PlufWO6.IsPluf σ ∧ R ⊆ σ := by
  classical
  set π : Set (Submodule ℝ E) := {K | IsClosed (K : Set E) ∧ ∃ M ∈ R, M ≤ K} with hπdef
  have hne_bot : ∀ M ∈ R, M ≠ ⊥ := by
    intro M hM hMbot
    refine hinf {M} ?_ ?_
    · simpa using Set.singleton_subset_iff.mpr hM
    · have : ({M} : Finset (Submodule ℝ E)).inf id = M := by simp
      rw [this, hMbot]
      exact Module.Finite.iff_fg.mpr Submodule.fg_bot
  have hprop : IsProperFilter π := by
    obtain ⟨M₀, hM₀⟩ := hne
    refine ⟨fun K hK => hK.1, ⟨M₀, hcl M₀ hM₀, M₀, hM₀, le_rfl⟩, ?_, ?_, ?_⟩
    · rintro K ⟨-, M, hM, hle⟩ K' hK' hKK'
      exact ⟨hK', M, hM, hle.trans hKK'⟩
    · rintro K ⟨hKcl, M, hM, hle⟩ K' ⟨hK'cl, M', hM', hle'⟩
      obtain ⟨P, hP, hPle⟩ := hdir M hM M' hM'
      exact ⟨PlufWO6.isClosed_inf hKcl hK'cl, P, hP,
        le_inf (hPle.trans (inf_le_left.trans hle)) (hPle.trans (inf_le_right.trans hle'))⟩
    · rintro ⟨-, M, hM, hle⟩
      exact hne_bot M hM (le_bot_iff.mp hle)
  obtain ⟨σ, hσ, hπσ⟩ := exists_pluf_extension π hprop
  exact ⟨σ, hσ, fun M hM => hπσ ⟨hcl M hM, M, hM, le_rfl⟩⟩

/-! ### Part B: chains and their coordinatization -/

section Chain

variable (M : ℕ → Submodule ℝ E)

/-- The pieces of the relative-complement decomposition of a nested chain
    `M 0 ≥ M 1 ≥ ⋯`, reindexed into a single `ℕ`-indexed family (which is
    the shape the countable-decomposition theorem consumes):

    * `chainPieces M 0 = (M 0)ᗮ`, the top complement;
    * `chainPieces M 1 = ⨅ k, M k`, the intersection of the chain;
    * `chainPieces M (n+2) = M n ⊓ (M (n+1))ᗮ`, the successive
      differences `M n ⊖ M (n+1)`. -/
noncomputable def chainPieces : ℕ → Submodule ℝ E
  | 0 => (M 0)ᗮ
  | 1 => ⨅ k, M k
  | (n+2) => M n ⊓ (M (n+1))ᗮ

omit [CompleteSpace E] in
@[simp] theorem chainPieces_zero : chainPieces M 0 = (M 0)ᗮ := rfl

omit [CompleteSpace E] in
@[simp] theorem chainPieces_one : chainPieces M 1 = ⨅ k, M k := rfl

omit [CompleteSpace E] in
@[simp] theorem chainPieces_succ_succ (n : ℕ) :
    chainPieces M (n+2) = M n ⊓ (M (n+1))ᗮ := rfl

variable {M}

omit [CompleteSpace E] in
/-- A nested chain is antitone. -/
theorem chain_le_of_le (hmono : ∀ k, M (k+1) ≤ M k) {i j : ℕ} (hij : i ≤ j) :
    M j ≤ M i := by
  induction j with
  | zero => simpa using (Nat.le_zero.mp hij) ▸ le_rfl
  | succ n ih =>
    rcases Nat.lt_or_ge i (n+1) with h | h
    · exact (hmono n).trans (ih (Nat.lt_succ_iff.mp h))
    · have : i = n + 1 := le_antisymm hij h
      exact this ▸ le_rfl

omit [CompleteSpace E] in
/-- Each piece is either inside `M k` or orthogonal to it. -/
theorem chainPieces_le_or_orthogonal (hmono : ∀ k, M (k+1) ≤ M k) (n k : ℕ) :
    chainPieces M n ≤ M k ∨ chainPieces M n ≤ (M k)ᗮ := by
  match n with
  | 0 =>
    exact Or.inr (Submodule.orthogonal_le (chain_le_of_le hmono (Nat.zero_le k)))
  | 1 =>
    exact Or.inl (by simpa using iInf_le M k)
  | (j+2) =>
    rcases Nat.lt_or_ge j k with h | h
    · refine Or.inr ((inf_le_right).trans ?_)
      exact Submodule.orthogonal_le (chain_le_of_le hmono h)
    · exact Or.inl (inf_le_left.trans (chain_le_of_le hmono h))

omit [CompleteSpace E] in
/-- The pieces are closed. -/
theorem isClosed_chainPieces (hcl : ∀ k, IsClosed (M k : Set E)) (n : ℕ) :
    IsClosed ((chainPieces M n : Submodule ℝ E) : Set E) := by
  match n with
  | 0 => exact Submodule.isClosed_orthogonal _
  | 1 =>
    have : ((⨅ k, M k : Submodule ℝ E) : Set E) = ⋂ k, (M k : Set E) := by
      simp
    rw [chainPieces_one, this]
    exact isClosed_iInter hcl
  | (j+2) => exact PlufWO6.isClosed_inf (hcl j) (Submodule.isClosed_orthogonal _)

omit [CompleteSpace E] in
/-- The pieces are pairwise orthogonal. -/
theorem chainPieces_pairwise_orthogonal (hmono : ∀ k, M (k+1) ≤ M k) :
    Pairwise fun m n => ∀ x ∈ chainPieces M m, ∀ y ∈ chainPieces M n,
      inner (𝕜 := ℝ) x y = 0 := by
  have key : ∀ m n : ℕ, m < n → ∃ k : ℕ,
      (chainPieces M m ≤ M k ∧ chainPieces M n ≤ (M k)ᗮ) ∨
      (chainPieces M n ≤ M k ∧ chainPieces M m ≤ (M k)ᗮ) := by
    intro m n hmn
    match m, n with
    | 0, n =>
      refine ⟨0, Or.inr ⟨?_, le_rfl⟩⟩
      match n with
      | 0 => exact absurd hmn (lt_irrefl 0)
      | 1 => simpa using iInf_le M 0
      | (j+2) => exact inf_le_left.trans (chain_le_of_le hmono (Nat.zero_le j))
    | 1, n =>
      match n with
      | 0 => exact absurd hmn (by omega)
      | 1 => exact absurd hmn (lt_irrefl 1)
      | (j+2) =>
        exact ⟨j+1, Or.inl ⟨by simpa using iInf_le M (j+1), inf_le_right⟩⟩
    | (i+2), n =>
      match n with
      | 0 => exact absurd hmn (by omega)
      | 1 => exact absurd hmn (by omega)
      | (j+2) =>
        have hij : i < j := by omega
        refine ⟨i+1, Or.inr ⟨?_, inf_le_right⟩⟩
        exact inf_le_left.trans (chain_le_of_le hmono hij)
  have main : ∀ m n : ℕ, m < n → ∀ x ∈ chainPieces M m, ∀ y ∈ chainPieces M n,
      inner (𝕜 := ℝ) x y = 0 := by
    intro m n hmn x hx y hy
    obtain ⟨k, hk | hk⟩ := key m n hmn
    · have := hk.2 hy
      exact this x (hk.1 hx)
    · have := hk.2 hx
      have h0 := this y (hk.1 hy)
      rw [real_inner_comm]
      exact h0
  intro m n hmn
  rcases lt_or_gt_of_ne hmn with h | h
  · exact main m n h
  · intro x hx y hy
    rw [real_inner_comm]
    exact main n m h y hy x hx

/-- Density of the join of the pieces, in the orthogonal-complement form
    the coordinatization consumes. -/
theorem chainPieces_orthogonal_eq_bot (hmono : ∀ k, M (k+1) ≤ M k)
    (hcl : ∀ k, IsClosed (M k : Set E)) :
    (⨆ n, chainPieces M n)ᗮ = ⊥ := by
  rw [Submodule.eq_bot_iff]
  intro z hz
  have hzperp : ∀ n, ∀ u ∈ chainPieces M n, inner (𝕜 := ℝ) u z = 0 := by
    intro n u hu
    exact hz u (le_iSup (fun n => chainPieces M n) n hu)
  haveI : ∀ k, CompleteSpace ↥(M k) := fun k => (hcl k).completeSpace_coe
  -- `z` lies in `M 0`
  have h0 : z ∈ M 0 := by
    have : z ∈ (M 0)ᗮᗮ := by
      intro u hu
      exact hzperp 0 u (by simpa using hu)
    rwa [Submodule.orthogonal_orthogonal] at this
  -- and inductively in every `M k`
  have hall : ∀ k, z ∈ M k := by
    intro k
    induction k with
    | zero => exact h0
    | succ n ih =>
      set u := (M (n+1)).starProjection z with hu
      have humem : u ∈ M (n+1) := (M (n+1)).starProjection_apply_mem z
      have hv : z - u ∈ (M (n+1))ᗮ := (M (n+1)).sub_starProjection_mem_orthogonal (v := z)
      have hvM : z - u ∈ M n := by
        refine Submodule.sub_mem _ ih ?_
        exact (hmono n) humem
      have hvpiece : z - u ∈ chainPieces M (n+2) := ⟨hvM, hv⟩
      have h1 : inner (𝕜 := ℝ) (z - u) z = 0 := hzperp (n+2) _ hvpiece
      have h2 : inner (𝕜 := ℝ) (z - u) u = 0 := by
        have := hv u humem
        rw [real_inner_comm]
        exact this
      have h3 : inner (𝕜 := ℝ) (z - u) (z - u) = 0 := by
        rw [inner_sub_right, h1, h2, sub_zero]
      have : z - u = 0 := inner_self_eq_zero.mp h3
      have hzu : z = u := by linear_combination (norm := module) this
      rw [hzu]
      exact humem
  have hzin : z ∈ chainPieces M 1 := by
    simpa using Submodule.mem_iInf _ |>.mpr hall
  have := hzperp 1 z hzin
  exact inner_self_eq_zero.mp this

/-- B1 (relative orthogonal complements). For a nested chain
    `M 0 ≥ M 1 ≥ ⋯` of closed subspaces, the successive differences
    `M k ⊖ M (k+1) = M k ⊓ (M (k+1))ᗮ`, the intersection `⋂ k, M k`, and
    the top complement `(M 0)ᗮ` are pairwise orthogonal closed subspaces
    whose closed span is everything. This is the decomposition the
    coordinatization consumes; state it in the form WO-9's corrected
    countable-decomposition theorem expects (an ℕ-indexed orthogonal
    family with dense span), reindexing the three groups into one
    sequence — the reindexing is bookkeeping and its shape is the
    prover's choice, reported.

    The contract left the statement open (`True`). The shape delivered is
    the family `chainPieces M` above, with the three clauses that the
    density variant of WO-9's D4 consumes: closedness, pairwise
    orthogonality, and density of the join, the last one in the form
    `(⨆ n, chainPieces M n)ᗮ = ⊥` (equivalent to density of the join,
    and what the basis construction actually uses). -/
theorem chain_decomposition (hmono : ∀ k, M (k+1) ≤ M k)
    (hcl : ∀ k, IsClosed (M k : Set E)) :
    (∀ n, IsClosed ((chainPieces M n : Submodule ℝ E) : Set E)) ∧
    (Pairwise fun m n => ∀ x ∈ chainPieces M m, ∀ y ∈ chainPieces M n,
      inner (𝕜 := ℝ) x y = 0) ∧
    (⨆ n, chainPieces M n)ᗮ = ⊥ :=
  ⟨isClosed_chainPieces hcl, chainPieces_pairwise_orthogonal hmono,
    chainPieces_orthogonal_eq_bot hmono hcl⟩

/-  B2, contract statement, preserved verbatim:

theorem exists_basis_blocks_of_chain [SeparableSpace E]
    (hmono : ∀ k, M (k+1) ≤ M k) (hcl : ∀ k, IsClosed (M k : Set E)) :
    ∃ b : HilbertBasis ℕ ℝ E, ∀ k, ∃ S : Set ℕ, M k = PlufWO9.blockB b S

    This form is not provable: nothing in the hypotheses makes `E`
    infinite-dimensional, and a finite-dimensional `E` has no `ℕ`-indexed
    Hilbert basis at all (an `ℕ`-indexed Hilbert basis is in particular an
    infinite orthonormal family). Taking `E = ℝ` — separable, complete —
    and the constant chain `M k = ⊤` satisfies every hypothesis and
    refutes the conclusion; see `exists_basis_blocks_of_chain_false`.
    The marked minimal repair adds the single hypothesis
    `hinf : ¬ FiniteDimensional ℝ E`, which is what the paper's ambient
    setting (a separable infinite-dimensional Hilbert space) supplies, and
    is the version proved below under the contracted name. -/

/-- B2 (simultaneous coordinatization; the analytic content of Paper II,
    Proposition 6.1), **minimal repair**: the extra hypothesis
    `hinf : ¬ FiniteDimensional ℝ E` (see the comment above and
    `exists_basis_blocks_of_chain_false`).

    A countable nested chain of closed subspaces of a separable
    infinite-dimensional Hilbert space admits an orthonormal basis,
    indexed by ℕ, for which every `M k` is a block:
    `M k = blockB b (S k)` for some `S k ⊆ ℕ`.

    Separability is contracted as a hypothesis, as instructed; it is
    automatic in the intended application, since `PlufWO1.H = ℓ²(ℕ; ℝ)`
    is separable (and infinite-dimensional, so the repair hypothesis is
    also automatic there). -/
theorem exists_basis_blocks_of_chain [TopologicalSpace.SeparableSpace E]
    (hinf : ¬ FiniteDimensional ℝ E)
    (hmono : ∀ k, M (k+1) ≤ M k) (hcl : ∀ k, IsClosed (M k : Set E)) :
    ∃ b : HilbertBasis ℕ ℝ E, ∀ k, ∃ S : Set ℕ, M k = PlufWO9.blockB b S := by
  obtain ⟨b, hb⟩ := exists_hilbertBasis_nat_of_orthogonal_family hinf (chainPieces M)
    (isClosed_chainPieces hcl) (chainPieces_pairwise_orthogonal hmono)
    (chainPieces_orthogonal_eq_bot hmono hcl)
  refine ⟨b, fun k => ⟨{i | b i ∈ M k}, ?_⟩⟩
  refine eq_blockB_of_basis_mem_or_orthogonal b (M k) (hcl k) (fun i => ?_)
  obtain ⟨n, hn⟩ := hb i
  rcases chainPieces_le_or_orthogonal hmono n k with h | h
  · exact Or.inl (h hn)
  · exact Or.inr (h hn)

end Chain

/-- The counterexample refuting the contracted form of B2: over `E = ℝ`
    the constant chain `M k = ⊤` satisfies every hypothesis, but `ℝ` has
    no `ℕ`-indexed Hilbert basis. -/
theorem no_hilbertBasis_nat_real : IsEmpty (HilbertBasis ℕ ℝ ℝ) := by
  refine ⟨fun b => ?_⟩
  have h01 : inner (𝕜 := ℝ) (b 0) (b 1) = 0 := b.orthonormal.2 (by norm_num)
  have h0 : ‖b 0‖ = 1 := b.orthonormal.1 0
  have h1 : ‖b 1‖ = 1 := b.orthonormal.1 1
  have hb0 : b 0 ≠ 0 := by
    intro h; rw [h] at h0; simp at h0
  have hb1 : b 1 ≠ 0 := by
    intro h; rw [h] at h1; simp at h1
  have : b 1 * b 0 = 0 := by simpa [RCLike.inner_apply] using h01
  rcases mul_eq_zero.mp this with h | h
  · exact hb1 h
  · exact hb0 h

theorem exists_basis_blocks_of_chain_false :
    ¬ (∀ (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
        [TopologicalSpace.SeparableSpace E] (M : ℕ → Submodule ℝ E),
        (∀ k, M (k+1) ≤ M k) → (∀ k, IsClosed (M k : Set E)) →
        ∃ b : HilbertBasis ℕ ℝ E, ∀ k, ∃ S : Set ℕ, M k = PlufWO9.blockB b S) := by
  intro h
  obtain ⟨b, -⟩ := h ℝ (fun _ => ⊤) (fun _ => le_rfl)
    (fun _ => by simp)
  exact no_hilbertBasis_nat_real.elim b

/-! ### Part C: blocks are intimate for their own basis -/

/-- Intimacy relative to an arbitrary basis (the basis-relative form of
    `PlufWO5.Intimate`, which is stated for the standard basis of
    `PlufWO1.H`). Reconcile the two: at the standard basis they should
    agree definitionally, by WO-9's `blockB` agreement lemma. Report the
    reconciliation. -/
def IntimateB {ι : Type*} (b : HilbertBasis ι ℝ E) (M : Submodule ℝ E) : Prop :=
  ∀ A : Set ι, M ⊓ PlufWO9.blockB b A ≠ ⊥ ∨ M ⊓ PlufWO9.blockB b Aᶜ ≠ ⊥

/-- The reconciliation asked for by the contract: at the standard basis of
    `PlufWO1.H`, `IntimateB` *is* `PlufWO5.Intimate` — the two are equal
    as predicates, by WO-9's agreement lemma `blockB_stdBasis_eq`. -/
theorem intimateB_stdHilbertBasis_iff (M : Submodule ℝ PlufWO1.H) :
    IntimateB PlufWO9.stdHilbertBasis M ↔ PlufWO5.Intimate M := by
  unfold IntimateB PlufWO5.Intimate
  simp only [PlufWO9.blockB_stdBasis_eq]

/-- C1 (blocks are intimate for their own basis; Paper II,
    Proposition 6.1, second half). If `B ⊆ ι` is nonempty then
    `blockB b B` is `b`-intimate: for any splitting `A ⊔ Aᶜ`, one side
    meets `B`, and `blockB b B ⊓ blockB b A = blockB b (B ∩ A)`, which is
    nonzero when `B ∩ A` is. The identity `blockB b B ⊓ blockB b A =
    blockB b (B ∩ A)` should be proved separately and exported — WO-12
    will want it. -/
theorem blockB_inf_blockB {ι : Type*} (b : HilbertBasis ι ℝ E) (B A : Set ι) :
    PlufWO9.blockB b B ⊓ PlufWO9.blockB b A = PlufWO9.blockB b (B ∩ A) := by
  ext x
  simp only [Submodule.mem_inf, PlufWO9.mem_blockB_iff]
  constructor
  · rintro ⟨hB, hA⟩ i hi
    rcases not_and_or.mp hi with h | h
    · exact hB i h
    · exact hA i h
  · intro h
    exact ⟨fun i hi => h i (fun hmem => hi hmem.1), fun i hi => h i (fun hmem => hi hmem.2)⟩

omit [CompleteSpace E] in
/-- The block of a nonempty set of indices is nonzero. -/
theorem blockB_ne_bot {ι : Type*} (b : HilbertBasis ι ℝ E) {B : Set ι} (hB : B.Nonempty) :
    PlufWO9.blockB b B ≠ ⊥ := by
  obtain ⟨i, hi⟩ := hB
  intro hbot
  have hmem : b i ∈ PlufWO9.blockB b B :=
    Submodule.le_topologicalClosure _ (Submodule.subset_span ⟨i, hi, rfl⟩)
  rw [hbot] at hmem
  have : b i = 0 := by simp at hmem; exact hmem
  have hnorm : ‖b i‖ = 1 := b.orthonormal.1 i
  rw [this] at hnorm
  simp at hnorm

omit [CompleteSpace E] in
/-- The block of the empty set of indices is zero. -/
theorem blockB_empty {ι : Type*} (b : HilbertBasis ι ℝ E) :
    PlufWO9.blockB b (∅ : Set ι) = ⊥ := by
  refine le_antisymm ?_ bot_le
  refine Submodule.topologicalClosure_minimal _ ?_ ?_
  · simp
  · simp

theorem intimateB_blockB {ι : Type*} (b : HilbertBasis ι ℝ E) (B : Set ι)
    (hB : B.Nonempty) :
    IntimateB b (PlufWO9.blockB b B) := by
  intro A
  obtain ⟨i, hi⟩ := hB
  by_cases hiA : i ∈ A
  · refine Or.inl ?_
    rw [blockB_inf_blockB]
    exact blockB_ne_bot b ⟨i, hi, hiA⟩
  · refine Or.inr ?_
    rw [blockB_inf_blockB]
    exact blockB_ne_bot b ⟨i, hi, hiA⟩

omit [CompleteSpace E] in
/-- C2 (upward inheritance of intimacy). Any closed subspace containing an
    intimate subspace is intimate. (Monotonicity of `⊓`; the paper uses
    this for "every enlargement of a member".) -/
theorem intimateB_mono {ι : Type*} (b : HilbertBasis ι ℝ E)
    {M N : Submodule ℝ E} (hM : IntimateB b M) (hMN : M ≤ N) :
    IntimateB b N := by
  intro A
  rcases hM A with h | h
  · exact Or.inl (fun hbot => h (le_bot_iff.mp (hbot ▸ inf_le_inf_right _ hMN)))
  · exact Or.inr (fun hbot => h (le_bot_iff.mp (hbot ▸ inf_le_inf_right _ hMN)))

/-! ### Part D: Proposition 6.1, as printed -/

/-  D1, contract statement, preserved verbatim:

theorem chains_never_suffice [SeparableSpace E] (M : ℕ → Submodule ℝ E)
    (hmono : ∀ k, M (k+1) ≤ M k) (hcl : ∀ k, IsClosed (M k : Set E))
    (hne : ∀ k, M k ≠ ⊥) :
    ∃ b : HilbertBasis ℕ ℝ E, ∀ k, ∀ N : Submodule ℝ E, M k ≤ N →
      IntimateB b N

    This form is not provable, for exactly the reason B2 is not: over the
    separable complete space `E = ℝ` the chain `M k = ⊤` satisfies every
    hypothesis (`⊤ ≠ ⊥` in `ℝ`) and there is no `HilbertBasis ℕ ℝ ℝ`; see
    `chains_never_suffice_false`. The marked minimal repair adds the
    hypothesis `hinf : ¬ FiniteDimensional ℝ E`, the paper's standing
    assumption on the ambient space, and is proved below under the
    contracted name. -/

/-- D1 (Chains never suffice; Paper II, Proposition 6.1), **minimal
    repair**: the extra hypothesis `hinf : ¬ FiniteDimensional ℝ E` (see
    the comment above and `chains_never_suffice_false`).

    For a countable nested chain of closed subspaces of a separable
    infinite-dimensional Hilbert space there is a basis making every
    member a block; consequently every member, and every closed subspace
    containing a member, is intimate for that basis — so no countable
    chain witnesses the hypothesis of Proposition 5.5. -/
theorem chains_never_suffice [TopologicalSpace.SeparableSpace E]
    (hinf : ¬ FiniteDimensional ℝ E) (M : ℕ → Submodule ℝ E)
    (hmono : ∀ k, M (k+1) ≤ M k) (hcl : ∀ k, IsClosed (M k : Set E))
    (hne : ∀ k, M k ≠ ⊥) :
    ∃ b : HilbertBasis ℕ ℝ E, ∀ k, ∀ N : Submodule ℝ E, M k ≤ N →
      IntimateB b N := by
  obtain ⟨b, hb⟩ := exists_basis_blocks_of_chain hinf hmono hcl
  refine ⟨b, fun k N hN => ?_⟩
  obtain ⟨S, hS⟩ := hb k
  have hSne : S.Nonempty := by
    rcases Set.eq_empty_or_nonempty S with rfl | h
    · exact absurd (hS.trans (blockB_empty b)) (hne k)
    · exact h
  exact intimateB_mono b (hS ▸ intimateB_blockB b S hSne) hN

/-- The counterexample refuting the contracted form of D1. -/
theorem chains_never_suffice_false :
    ¬ (∀ (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
        [TopologicalSpace.SeparableSpace E] (M : ℕ → Submodule ℝ E),
        (∀ k, M (k+1) ≤ M k) → (∀ k, IsClosed (M k : Set E)) → (∀ k, M k ≠ ⊥) →
        ∃ b : HilbertBasis ℕ ℝ E, ∀ k, ∀ N : Submodule ℝ E, M k ≤ N → IntimateB b N) := by
  intro h
  obtain ⟨b, -⟩ := h ℝ (fun _ => ⊤) (fun _ => le_rfl)
    (fun _ => by simp)
    (fun _ => by
      intro htop
      have h1 : (1 : ℝ) ∈ (⊥ : Submodule ℝ ℝ) := htop ▸ Submodule.mem_top
      simp at h1)
  exact no_hilbertBasis_nat_real.elim b

/-! ### Part E: Proposition 5.5, as printed -/

/-! #### E0: the basis-relative form of Paper II, Theorem 5.2

The design question of the work order is answered affirmatively: the proof
of `PlufWO5.diagonalizable_iff_intimate` uses only the lattice identities
of blocks, all of which hold at an arbitrary Hilbert basis
(`blockB_inf_blockB`, `blockB_mono`, `blockB_univ`, `blockB_empty`), so
the generalization is cheap and is proved here. -/

theorem blockB_mono {ι : Type*} (b : HilbertBasis ι ℝ E) {S T : Set ι} (hST : S ⊆ T) :
    PlufWO9.blockB b S ≤ PlufWO9.blockB b T := by
  intro x hx
  rw [PlufWO9.mem_blockB_iff] at hx ⊢
  exact fun i hi => hx i (fun h => hi (hST h))

theorem blockB_univ {ι : Type*} (b : HilbertBasis ι ℝ E) :
    PlufWO9.blockB b (Set.univ : Set ι) = ⊤ := by
  refine Submodule.eq_top_iff'.mpr (fun x => ?_)
  rw [PlufWO9.mem_blockB_iff]
  intro i hi
  exact absurd (Set.mem_univ i) hi

omit [CompleteSpace E] in
/-- The easy direction of E0, which is all Proposition 5.5 needs:
    if the block trace of `π` is an ultrafilter, every member of `π` is
    intimate for that basis. -/
theorem intimateB_of_diagonalizableB {ι : Type*} (b : HilbertBasis ι ℝ E)
    (π : Set (Submodule ℝ E))
    (hinf : ∀ M ∈ π, ∀ N ∈ π, M ⊓ N ∈ π)
    (hbot : (⊥ : Submodule ℝ E) ∉ π)
    (hdiag : ∃ V : Ultrafilter ι, ∀ S : Set ι, S ∈ V ↔ PlufWO9.blockB b S ∈ π) :
    ∀ M ∈ π, IntimateB b M := by
  obtain ⟨V, hV⟩ := hdiag
  intro M hM A
  rcases V.mem_or_compl_mem A with hA | hA
  · refine Or.inl (fun hbot' => hbot ?_)
    have := hinf M hM (PlufWO9.blockB b A) ((hV A).mp hA)
    rwa [hbot'] at this
  · refine Or.inr (fun hbot' => hbot ?_)
    have := hinf M hM (PlufWO9.blockB b Aᶜ) ((hV Aᶜ).mp hA)
    rwa [hbot'] at this

/-- E0 (the basis-relative form of Paper II, Theorem 5.2). A family of
    closed subspaces with the package properties, at an arbitrary Hilbert
    basis `b`, is `b`-diagonalizable — its `b`-block trace is an
    ultrafilter — iff every member is `b`-intimate.

    The package clause `finCodim_mem` of `PlufWO5.PlufPackage` is used in
    WO-5's proof only to place `⊤` in the family, so it is contracted here
    in that weaker form. -/
theorem diagonalizableB_iff_intimateB {ι : Type*} (b : HilbertBasis ι ℝ E)
    (π : Set (Submodule ℝ E))
    (hup : ∀ M ∈ π, ∀ N : Submodule ℝ E, IsClosed (N : Set E) → M ≤ N → N ∈ π)
    (hinf : ∀ M ∈ π, ∀ N ∈ π, M ⊓ N ∈ π)
    (hbot : (⊥ : Submodule ℝ E) ∉ π)
    (htop : (⊤ : Submodule ℝ E) ∈ π)
    (hdec : ∀ M : Submodule ℝ E, IsClosed (M : Set E) →
      M ∈ π ∨ ∃ N ∈ π, M ⊓ N = ⊥) :
    (∃ V : Ultrafilter ι, ∀ S : Set ι, S ∈ V ↔ PlufWO9.blockB b S ∈ π) ↔
      (∀ M ∈ π, IntimateB b M) := by
  constructor
  · intro hdiag
    exact intimateB_of_diagonalizableB b π hinf hbot hdiag
  · intro hint
    set F : Filter ι :=
      { sets := {S | PlufWO9.blockB b S ∈ π}
        univ_sets := by
          show PlufWO9.blockB b univ ∈ π
          rw [blockB_univ]
          exact htop
        sets_of_superset := by
          intro S T hS hST
          exact hup _ hS _ (PlufWO9.isClosed_blockB b T) (blockB_mono b hST)
        inter_sets := by
          intro S T hS hT
          show PlufWO9.blockB b (S ∩ T) ∈ π
          rw [← blockB_inf_blockB]
          exact hinf _ hS _ hT } with hF
    have hmemF : ∀ S : Set ι, S ∈ F ↔ PlufWO9.blockB b S ∈ π := fun _ => Iff.rfl
    have hdich : ∀ S : Set ι, PlufWO9.blockB b S ∈ π ∨ PlufWO9.blockB b Sᶜ ∈ π := by
      intro S
      by_contra hcon
      push_neg at hcon
      obtain ⟨N, hN, hNbot⟩ :=
        (hdec (PlufWO9.blockB b S) (PlufWO9.isClosed_blockB b S)).resolve_left hcon.1
      obtain ⟨N', hN', hN'bot⟩ :=
        (hdec (PlufWO9.blockB b Sᶜ) (PlufWO9.isClosed_blockB b Sᶜ)).resolve_left hcon.2
      have hMπ : N ⊓ N' ∈ π := hinf N hN N' hN'
      rcases hint (N ⊓ N') hMπ S with h | h
      · refine h (le_bot_iff.mp (le_trans (inf_le_inf_right (PlufWO9.blockB b S) inf_le_left)
          (le_of_eq ?_)))
        rw [inf_comm] at hNbot; exact hNbot
      · refine h (le_bot_iff.mp (le_trans (inf_le_inf_right (PlufWO9.blockB b Sᶜ) inf_le_right)
          (le_of_eq ?_)))
        rw [inf_comm] at hN'bot; exact hN'bot
    have hult : ∀ S : Set ι, Sᶜ ∉ F ↔ S ∈ F := by
      intro S
      constructor
      · intro h
        exact (hdich S).resolve_right (fun hc => h ((hmemF Sᶜ).mpr hc))
      · intro hS hSc
        refine hbot ?_
        have := hinf _ ((hmemF S).mp hS) _ ((hmemF Sᶜ).mp hSc)
        rwa [blockB_inf_blockB, inter_compl_self, blockB_empty] at this
    exact ⟨Ultrafilter.ofComplNotMemIff F hult, fun S => hmemF S⟩

/-- E1 (One-witness reduction; Paper II, Proposition 5.5). Let `R` be a
    downward directed family of closed subspaces, all finite intersections
    infinite-dimensional, with `⨅ R = ⊥`, such that every orthonormal
    basis admits a member of `R` that is not intimate for it. Then every
    pluf extending `R` is nonprincipal and non-diagonalizable, and such
    plufs exist.

    Route: existence is A2; nonprincipality is `⨅ R = ⊥` against
    `PlufWO6.principal_iff_sInf_ne_bot`; non-diagonalizability via a given
    basis is the witness member together with WO-6's
    `diagonalizable_iff_intimate_pluf` (the package-discharged form of
    Paper II's Theorem 5.2).

    NOTE ON THE BASIS QUANTIFIER. Theorem 5.2 as mechanized speaks of the
    standard basis of `PlufWO1.H`; Proposition 5.5 quantifies over all
    orthonormal bases. Bridging requires the basis-relative form of
    Theorem 5.2 — i.e. `diagonalizable_iff_intimate` stated with `blockB b`
    in place of `block`. If that generalization is cheap (WO-9's `blockB`
    API and D3 reindexing should make it so, since the proof of Theorem 5.2
    uses only the lattice identities of blocks), PROVE IT as item E0 and
    use it; if it is not, state E1 for a fixed basis and REPORT the gap —
    do not silently specialize the printed statement.

    Verdict on E0: it is cheap, it is proved above as
    `diagonalizableB_iff_intimateB`, and E1 is proved as printed, at all
    bases. In fact only the easy direction of E0 is needed
    (`intimateB_of_diagonalizableB`), which uses nothing but closure of a
    pluf under meets and properness. -/
theorem one_witness_reduction (R : Set (Submodule ℝ PlufWO1.H))
    (hne : R.Nonempty)
    (hcl : ∀ M ∈ R, IsClosed (M : Set PlufWO1.H))
    (hdir : ∀ M ∈ R, ∀ N ∈ R, ∃ P ∈ R, P ≤ M ⊓ N)
    (hinfdim : ∀ F : Finset (Submodule ℝ PlufWO1.H), ↑F ⊆ R →
      ¬ Module.Finite ℝ ↥(F.inf id))
    (hsInf : sInf R = ⊥)
    (hwitness : ∀ b : HilbertBasis ℕ ℝ PlufWO1.H, ∃ M ∈ R, ¬ IntimateB b M) :
    (∃ σ, PlufWO6.IsPluf σ ∧ R ⊆ σ) ∧
    ∀ σ, PlufWO6.IsPluf σ → R ⊆ σ →
      (∀ v : PlufWO1.H, v ≠ 0 → ∃ N ∈ σ, v ∉ N) ∧
      ∀ b : HilbertBasis ℕ ℝ PlufWO1.H,
        ¬ ∃ V : Ultrafilter ℕ, ∀ S : Set ℕ, S ∈ V ↔ PlufWO9.blockB b S ∈ σ := by
  refine ⟨exists_pluf_of_directed R hne hcl hdir hinfdim, fun σ hσ hRσ => ⟨?_, ?_⟩⟩
  · -- nonprincipality: a vector in every member of `σ` lies in `sInf R = ⊥`
    intro v hv
    by_contra hcon
    push_neg at hcon
    have hmem : v ∈ sInf R := by
      rw [Submodule.mem_sInf]
      intro M hM
      exact hcon M (hRσ hM)
    rw [hsInf] at hmem
    exact hv (by simpa using hmem)
  · -- non-diagonalizability at every basis
    intro b hdiag
    obtain ⟨M, hM, hMnot⟩ := hwitness b
    exact hMnot (intimateB_of_diagonalizableB b σ hσ.inf_mem hσ.proper hdiag M (hRσ hM))

/-! ### Axiom audit -/

#print axioms exists_pluf_extension
#print axioms exists_pluf_of_directed
#print axioms chain_decomposition
#print axioms exists_basis_blocks_of_chain
#print axioms exists_basis_blocks_of_chain_false
#print axioms blockB_inf_blockB
#print axioms intimateB_blockB
#print axioms intimateB_mono
#print axioms intimateB_stdHilbertBasis_iff
#print axioms chains_never_suffice
#print axioms chains_never_suffice_false
#print axioms diagonalizableB_iff_intimateB
#print axioms one_witness_reduction

end PlufWO10
